---
- name: Check if K3s is already installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Download K3s installer
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'
  when: not k3s_installed.stat.exists

- name: Install K3s
  shell: |
    INSTALL_K3S_VERSION="{{ k3s_version }}" \
    INSTALL_K3S_EXEC="--cluster-cidr={{ k3s_cluster_cidr }} --service-cidr={{ k3s_service_cidr }}" \
    /tmp/k3s-install.sh
  when: not k3s_installed.stat.exists

- name: Wait for K3s to be ready
  wait_for:
    port: 6443
    delay: 10
    timeout: 300

- name: Create .kube directory for users
  file:
    path: "/home/{{ item }}/.kube"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0755'
  loop:
    - "{{ ansible_user }}"
    - ansible
  become: yes

- name: Copy k3s config to user kube config
  shell: |
    k3s kubectl config view --raw > /home/{{ item }}/.kube/config
  loop:
    - "{{ ansible_user }}"
    - ansible
  changed_when: false

- name: Set proper permissions on kube config
  file:
    path: "/home/{{ item }}/.kube/config"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0600'
  loop:
    - "{{ ansible_user }}"
    - ansible

- name: Install kubectl bash completion
  shell: |
    kubectl completion bash > /etc/bash_completion.d/kubectl
  args:
    creates: /etc/bash_completion.d/kubectl

- name: Add KUBECONFIG to user profiles
  lineinfile:
    path: "/home/{{ item }}/.bashrc"
    line: 'export KUBECONFIG=$HOME/.kube/config'
    state: present
  loop:
    - "{{ ansible_user }}"
    - ansible

- name: Install Helm
  block:
    - name: Download Helm installer script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'
    
    - name: Install Helm
      shell: |
        DESIRED_VERSION="{{ helm_version }}" /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm

- name: Install k9s for Kubernetes management
  apt:
    deb: https://github.com/derailed/k9s/releases/download/v0.32.4/k9s_linux_amd64.deb
    state: present

- name: Add Helm repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  loop: "{{ helm_repos }}"
  become_user: "{{ ansible_user }}"

- name: Update Helm repositories
  command: helm repo update
  become_user: "{{ ansible_user }}"
  changed_when: false